### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int32
b: <class 'torch.Tensor'>, torch.int32
c: <class 'torch.Tensor'>, torch.int32
d: <class 'numpy.ndarray'>, int32


### Function 1 -  torch.from_numpy() / tensor.numpy()

In [5]:
# Example 1 - transform ndarray to tensor
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a)

b = torch.from_numpy(a)
print(b)

a.shape, b.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=torch.int32)


((2, 2, 3), torch.Size([2, 2, 3]))

In [11]:
# Example 2 - tranform tensor to adarray
c = b.numpy()
print(c)

d = torch.rand_like(b, dtype=torch.float)         # 需要是 tensor 且 dtype 不一樣要做轉換
print(d) 

c.shape, d.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
tensor([[[0.6759, 0.4347, 0.9303],
         [0.4589, 0.8579, 0.9775]],

        [[0.9499, 0.6423, 0.1068],
         [0.3115, 0.4503, 0.0751]]])


((2, 2, 3), torch.Size([2, 2, 3]))

### Function 2 - torch.unsqueeze() / torch.squeeze()

In [13]:
# Example 1 - increase dimension

e = torch.unsqueeze(b, dim=2)
print(e)
e.shape

tensor([[[[ 1,  2,  3]],

         [[ 4,  5,  6]]],


        [[[ 7,  8,  9]],

         [[10, 11, 12]]]], dtype=torch.int32)


torch.Size([2, 2, 1, 3])

In [14]:
# Example 2 - decrease dimension，default the dim == 1

f = torch.squeeze(e)
print(f)
f.shape

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=torch.int32)


torch.Size([2, 2, 3])

### Function 3 - tensor.transpose() / tensor.permute()

In [15]:
# Example 1 - 交換維度
g = e.transpose(0,2)
print(g)
g.shape

tensor([[[[ 1,  2,  3],
          [ 7,  8,  9]],

         [[ 4,  5,  6],
          [10, 11, 12]]]], dtype=torch.int32)


torch.Size([1, 2, 2, 3])

In [16]:
# Example 2 - 重組維度
h = g.permute((3,2,1,0))
print(h)
h.shape

tensor([[[[ 1],
          [ 4]],

         [[ 7],
          [10]]],


        [[[ 2],
          [ 5]],

         [[ 8],
          [11]]],


        [[[ 3],
          [ 6]],

         [[ 9],
          [12]]]], dtype=torch.int32)


torch.Size([3, 2, 2, 1])

### Function 4 - tensor.reshape() / tensor.view()

In [17]:
# Example 1 - 改變形狀
i = h.reshape(3, 4)
print(i)

j = h.reshape(3, -1)
print(j)
i.shape, j.shape

tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]], dtype=torch.int32)
tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]], dtype=torch.int32)


(torch.Size([3, 4]), torch.Size([3, 4]))

In [18]:
# Example 2 - 改變形狀
k = h.view(3, 1, -1)
print(k)
k.shape

tensor([[[ 1,  4,  7, 10]],

        [[ 2,  5,  8, 11]],

        [[ 3,  6,  9, 12]]], dtype=torch.int32)


torch.Size([3, 1, 4])